### PR TITLE
wait for PostgreSQL to come up when starting a PostgreSQL container

### PR DESCRIPTION
**Pull request by znmeb**

### CODE REVIEW

**Comment by jimtyhurst** [comment]
These changes worked okay on my machine. However, the default `image_tag` value `docker.io/postgres:10` did not exist on my machine, so I needed to call the function with an explicit image name:tag:
```r
sp_pg_docker_run("sqlpet-wait", image_tag = "postgres-dvdrental:latest")
```
Should we make the default value to be something that a student has already loaded with previous function calls during set-up?

**Review by jimtyhurst — APPROVED** [review]

**Comment by znmeb** [comment]
@jimtyhurst If you didn't have postgres:10 it should have been downloaded - was it not?

**Comment by jimtyhurst** [comment]
Ed asked:
> If you didn't have postgres:10 it should have been downloaded - was it not?

I thought that it did not, but just now I could not reproduce that problem. So ignore that comment.

_Steps that I verified_
This time, I removed all of my `sql-pet`-related containers and images, then ran:
```r
sp_pg_docker_run("test-sqlpet")
```
As you expected, it installed the `postgres:10` image and created and started a container named `test-sqlpet`. Sorry about my previous erroneous error reporting!

**Comment by znmeb** [comment]
Updates since pull request opened:
1. Added functions to create a Docker network and to list Docker networks into a tibble.
2. Added a Docker network parameter to `sp_pg_docker_run`. The default name is "sql-pet" and the network is created if it doesn't exist. So all the old calls should work.

**Review by smithjd — APPROVED** [review]
Haven't run it but it looks good to me.

**Pull request merged**
